export const SITE_CONTACT_EMAIL = "contato@altixdev.com.br";

export const localeOptions = [
  { code: "pt-BR", label: "Português (Brasil)", flag: "🇧🇷" },
  { code: "en-US", label: "English (US)", flag: "🇺🇸" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "pt-PT", label: "Português (Portugal)", flag: "🇵🇹" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "nl", label: "Nederlands", flag: "🇳🇱" },
  { code: "en-GB", label: "English (UK)", flag: "🇬🇧" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "nb", label: "Norsk", flag: "🇳🇴" },
  { code: "ga", label: "Gaeilge", flag: "🇮🇪" },
] as const;

export type Locale = (typeof localeOptions)[number]["code"];
export const DEFAULT_LOCALE: Locale = "pt-BR";

type Card = { title: string; text: string };
type FaqItem = { question: string; answer: string };
type QuestionStep = { eyebrow: string; title: string; options: string[] };

export type SiteCopy = {
  metaTitle: string;
  languageLabel: string;
  nav: { solutions: string; process: string; diagnostic: string; start: string };
  hero: { badge: string; title: string; description: string; primaryCta: string; secondaryCta: string; highlights: string[] };
  heroPanel: { eyebrow: string; items: string[]; bottom: string };
  deliverables: string[];
  solutions: { eyebrow: string; title: string; description: string; cards: Card[] };
  friction: { eyebrow: string; title: string; description: string; cta: string; positiveTitle: string; positiveItems: string[]; negativeTitle: string; negativeItems: string[] };
  process: { eyebrow: string; title: string; description: string; steps: Card[] };
  faq: { eyebrow: string; title: string; items: FaqItem[] };
  diagnostic: {
    eyebrow: string;
    title: string;
    description: string;
    benefits: string[];
    progress: string;
    responseNotice: string;
    questionSteps: QuestionStep[];
    contactEyebrow: string;
    contactTitle: string;
    contactDescription: string;
    fields: { name: string; namePlaceholder: string; company: string; companyPlaceholder: string; email: string; phone: string; phonePlaceholder: string };
    consent: string;
    privacyNotice: string;
    back: string;
    continue: string;
    submit: string;
    submitting: string;
  };
  footerTagline: string;
  toasts: { chooseOption: string; consent: string; createLeadError: string };
  whatsappIntro: string;
};

const ptBR: SiteCopy = {
  metaTitle: "Altixdev — Site, WhatsApp e IA com contexto",
  languageLabel: "Idioma da página",
  nav: { solutions: "Soluções", process: "Como funciona", diagnostic: "Diagnóstico", start: "Começar diagnóstico" },
  hero: {
    badge: "Diagnóstico gratuito em 5 etapas",
    title: "Transforme visitas e mensagens em oportunidades com contexto.",
    description: "Wesley une site, automação de WhatsApp e IA para ajudar sua empresa a explicar melhor a oferta, responder com mais clareza e conduzir cada contato até o próximo passo.",
    primaryCta: "Ver meu diagnóstico gratuito",
    secondaryCta: "Entender o processo",
    highlights: ["Sem compromisso de contratação", "Resumo antes de abrir o WhatsApp"],
  },
  heroPanel: { eyebrow: "O que o diagnóstico organiza", items: ["Onde o lead entra hoje", "Qual ponto está esfriando a conversa", "O menor próximo passo para testar", "Como Wesley recebe o contexto"], bottom: "Você chega à conversa sem repetir tudo do zero." },
  deliverables: ["Diagnóstico do principal gargalo", "Direção de site, WhatsApp ou IA", "Resumo da conversa já contextualizado"],
  solutions: {
    eyebrow: "Soluções que se conectam",
    title: "Mais clareza na mensagem. Menos fricção no caminho até a venda.",
    description: "Cada solução existe para resolver uma parte da mesma jornada: atrair a pessoa certa, explicar a oferta e conduzir o contato com consistência.",
    cards: [
      { title: "Sites que posicionam", text: "Páginas que explicam sua solução, criam confiança e mostram com clareza o próximo passo." },
      { title: "WhatsApp que organiza", text: "Fluxos de atendimento para responder, qualificar e transferir o contexto ao seu time." },
      { title: "IA com limites claros", text: "Automação com temas aprovados, rota humana e melhoria contínua conforme a operação." },
    ],
  },
  friction: {
    eyebrow: "Onde a Altixdev ajuda mais",
    title: "Não comece pelo código. Comece pelo gargalo que está custando conversas.",
    description: "O diagnóstico é ideal para empresas que já recebem algum interesse, mas precisam transformar esforço em uma experiência mais clara para o lead e para a equipe.",
    cta: "Identificar meu gargalo",
    positiveTitle: "Bom momento para começar",
    positiveItems: ["Sua empresa recebe contatos, mas perde contexto.", "O site não deixa clara a diferença da sua solução.", "A equipe repete respostas ou demora a voltar.", "Você quer testar um fluxo antes de uma mudança maior."],
    negativeTitle: "O que não prometemos",
    negativeItems: ["Automação sem limite ou sem responsável humano.", "Resultado garantido sem entender a operação.", "Uma proposta genérica antes do diagnóstico.", "Contato insistente depois de você pedir para parar."],
  },
  process: {
    eyebrow: "Como funciona",
    title: "Wesley transforma tecnologia em uma jornada comercial mais simples.",
    description: "Você não precisa começar com um projeto gigante. A Altixdev começa entendendo o objetivo, o gargalo e a menor mudança capaz de gerar aprendizado antes de ampliar qualquer automação.",
    steps: [
      { title: "Descobrir", text: "Mapeamos objetivo, canal, gargalo e urgência." },
      { title: "Desenhar", text: "Conectamos mensagem, site, WhatsApp e pessoas." },
      { title: "Implantar", text: "Construímos com escopo, limites e responsáveis." },
      { title: "Evoluir", text: "Medimos, ajustamos e ampliamos o que faz sentido." },
    ],
  },
  faq: {
    eyebrow: "Antes de começar",
    title: "Dúvidas comuns, respondidas com clareza.",
    items: [
      { question: "O diagnóstico me obriga a contratar?", answer: "Não. Ele serve para organizar o contexto e indicar um caminho de conversa. Você decide se quer seguir depois." },
      { question: "Preciso já ter um site ou automação?", answer: "Não. O diagnóstico também é útil quando você quer entender por onde começar e qual prioridade faz mais sentido." },
      { question: "A IA substitui todo o atendimento?", answer: "Não. A Altixdev trabalha com limites, assuntos aprovados e encaminhamento humano quando o contexto pede uma pessoa." },
      { question: "O que acontece depois de enviar meus dados?", answer: "O lead é registrado no painel da Altixdev, o resumo é incluído na mensagem de WhatsApp e Wesley pode continuar a conversa se você autorizar." },
    ],
  },
  diagnostic: {
    eyebrow: "Diagnóstico guiado",
    title: "Encontre o próximo passo mais útil antes de pedir uma proposta.",
    description: "Em cinco etapas, você organiza o cenário. Ao final, Wesley recebe um resumo da necessidade e o WhatsApp abre com a conversa já preparada.",
    benefits: ["Você escolhe apenas respostas relevantes ao seu contexto.", "O registro evita que você precise explicar tudo novamente.", "O contato só continua se você consentir no formulário."],
    progress: "{{progress}}% concluído",
    responseNotice: "Sua resposta será usada apenas para montar um resumo mais útil para a conversa.",
    questionSteps: [
      { eyebrow: "01 · Resultado desejado", title: "O que você quer tornar mais eficiente agora?", options: ["Gerar mais oportunidades", "Converter mais contatos", "Reduzir tarefas manuais", "Organizar uma operação digital"] },
      { eyebrow: "02 · Canal atual", title: "Onde suas conversas e oportunidades começam hoje?", options: ["Instagram", "WhatsApp", "Indicação", "Site", "E-mail", "Outro"] },
      { eyebrow: "03 · Principal gargalo", title: "Qual ponto mais trava seu avanço?", options: ["Site não explica bem a solução", "Leads não recebem resposta a tempo", "Atendimento é muito repetitivo", "Falta de processo comercial"] },
      { eyebrow: "04 · Momento da decisão", title: "Qual é a urgência para resolver isso?", options: ["Quero começar nas próximas semanas", "Estou comparando soluções", "Quero estruturar o plano primeiro", "Ainda estou entendendo o problema"] },
    ],
    contactEyebrow: "05 · Seus dados",
    contactTitle: "Envie o resumo para sua conversa no WhatsApp.",
    contactDescription: "Registramos o diagnóstico no pipeline da Altixdev e abrimos o WhatsApp com o contexto já incluído.",
    fields: { name: "Nome", namePlaceholder: "Como podemos chamar você?", company: "Empresa", companyPlaceholder: "Nome da empresa", email: "E-mail", phone: "WhatsApp", phonePlaceholder: "(00) 00000-0000" },
    consent: "Autorizo a Altixdev a usar meus dados para responder ao meu pedido, enviar o resumo deste diagnóstico e fazer contato sobre esta oportunidade. Posso solicitar a interrupção do contato a qualquer momento.",
    privacyNotice: "Ao continuar, você verá a mensagem com suas respostas no WhatsApp. Não há envio automático de propostas nem inclusão em listas sem autorização.",
    back: "Voltar",
    continue: "Continuar",
    submit: "Ver resumo e falar no WhatsApp",
    submitting: "Salvando…",
  },
  footerTagline: "Tecnologia que prepara conversas melhores.",
  toasts: { chooseOption: "Escolha uma opção para continuar.", consent: "Confirme o consentimento para enviar o diagnóstico.", createLeadError: "Não conseguimos registrar seu diagnóstico. Revise os dados e tente novamente." },
  whatsappIntro: "Olá, Wesley! Concluí o diagnóstico da Altixdev e gostaria de conversar.",
};

const enUS: SiteCopy = {
  metaTitle: "Altixdev — Website, WhatsApp and AI with context",
  languageLabel: "Page language",
  nav: { solutions: "Solutions", process: "How it works", diagnostic: "Diagnostic", start: "Start diagnostic" },
  hero: { badge: "Free 5-step diagnostic", title: "Turn visits and messages into opportunities with context.", description: "Wesley combines websites, WhatsApp automation and AI to help your company explain its offer better, respond more clearly and guide each contact to the next step.", primaryCta: "Get my free diagnostic", secondaryCta: "Understand the process", highlights: ["No commitment to hire", "Summary before opening WhatsApp"] },
  heroPanel: { eyebrow: "What the diagnostic organizes", items: ["Where the lead enters today", "What is cooling down the conversation", "The smallest next step to test", "How Wesley receives the context"], bottom: "You reach the conversation without repeating everything from scratch." },
  deliverables: ["Diagnostic of the main bottleneck", "Direction for website, WhatsApp or AI", "Conversation summary already in context"],
  solutions: { eyebrow: "Connected solutions", title: "More clarity in the message. Less friction on the way to a sale.", description: "Every solution exists to solve a part of the same journey: attract the right person, explain the offer and guide the contact consistently.", cards: [{ title: "Websites that position", text: "Pages that explain your solution, build trust and clearly show the next step." }, { title: "WhatsApp that organizes", text: "Service flows to respond, qualify and transfer context to your team." }, { title: "AI with clear limits", text: "Automation with approved topics, a human route and continuous improvement as operations evolve." }] },
  friction: { eyebrow: "Where Altixdev helps most", title: "Do not start with code. Start with the bottleneck costing you conversations.", description: "The diagnostic is ideal for companies that already receive interest but need to turn effort into a clearer experience for leads and their team.", cta: "Identify my bottleneck", positiveTitle: "A good time to start", positiveItems: ["Your company receives contacts but loses context.", "Your website does not make your difference clear.", "The team repeats answers or takes too long to reply.", "You want to test a flow before a larger change."], negativeTitle: "What we do not promise", negativeItems: ["Automation without limits or a human owner.", "Guaranteed results without understanding operations.", "A generic proposal before the diagnostic.", "Persistent contact after you ask us to stop."] },
  process: { eyebrow: "How it works", title: "Wesley turns technology into a simpler commercial journey.", description: "You do not need to start with a huge project. Altixdev starts by understanding the goal, the bottleneck and the smallest change that can create learning before expanding any automation.", steps: [{ title: "Discover", text: "We map goal, channel, bottleneck and urgency." }, { title: "Design", text: "We connect message, website, WhatsApp and people." }, { title: "Implement", text: "We build with scope, limits and owners." }, { title: "Evolve", text: "We measure, adjust and expand what makes sense." }] },
  faq: { eyebrow: "Before you start", title: "Common questions, answered clearly.", items: [{ question: "Does the diagnostic require me to hire you?", answer: "No. It organizes the context and points to a possible conversation path. You decide whether to move forward." }, { question: "Do I need a website or automation already?", answer: "No. The diagnostic is also useful when you want to understand where to start and which priority makes sense." }, { question: "Does AI replace all customer service?", answer: "No. Altixdev works with limits, approved topics and human handoff when the context calls for a person." }, { question: "What happens after I send my details?", answer: "The lead is registered in the Altixdev panel, the summary is included in the WhatsApp message and Wesley can continue the conversation if you authorize it." }] },
  diagnostic: { eyebrow: "Guided diagnostic", title: "Find the most useful next step before asking for a proposal.", description: "In five steps, you organize the scenario. At the end, Wesley receives a summary of your need and WhatsApp opens with the conversation ready.", benefits: ["You choose only answers relevant to your context.", "The record keeps you from explaining everything again.", "Contact only continues if you consent in the form."], progress: "{{progress}}% complete", responseNotice: "Your answer will only be used to create a more useful summary for the conversation.", questionSteps: [{ eyebrow: "01 · Desired outcome", title: "What do you want to make more efficient now?", options: ["Generate more opportunities", "Convert more contacts", "Reduce manual tasks", "Organize a digital operation"] }, { eyebrow: "02 · Current channel", title: "Where do your conversations and opportunities start today?", options: ["Instagram", "WhatsApp", "Referral", "Website", "Email", "Other"] }, { eyebrow: "03 · Main bottleneck", title: "Which point slows your progress the most?", options: ["The website does not explain the solution well", "Leads do not receive a timely reply", "Service is too repetitive", "There is no sales process"] }, { eyebrow: "04 · Decision timing", title: "How urgent is it to solve this?", options: ["I want to start in the next few weeks", "I am comparing solutions", "I want to structure the plan first", "I am still understanding the problem"] }], contactEyebrow: "05 · Your details", contactTitle: "Send the summary to your WhatsApp conversation.", contactDescription: "We register the diagnostic in Altixdev's pipeline and open WhatsApp with the context included.", fields: { name: "Name", namePlaceholder: "How should we call you?", company: "Company", companyPlaceholder: "Company name", email: "Email", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "I authorize Altixdev to use my details to respond to my request, send this diagnostic summary and contact me about this opportunity. I can request that contact stop at any time.", privacyNotice: "By continuing, you will see the message with your answers in WhatsApp. There are no automatic proposals or list subscriptions without authorization.", back: "Back", continue: "Continue", submit: "View summary and talk on WhatsApp", submitting: "Saving…" },
  footerTagline: "Technology that prepares better conversations.",
  toasts: { chooseOption: "Choose an option to continue.", consent: "Confirm your consent to send the diagnostic.", createLeadError: "We could not register your diagnostic. Review the details and try again." },
  whatsappIntro: "Hello, Wesley! I completed the Altixdev diagnostic and would like to talk.",
};

const es: SiteCopy = {
  metaTitle: "Altixdev — Sitio web, WhatsApp e IA con contexto", languageLabel: "Idioma de la página", nav: { solutions: "Soluciones", process: "Cómo funciona", diagnostic: "Diagnóstico", start: "Empezar diagnóstico" },
  hero: { badge: "Diagnóstico gratuito en 5 pasos", title: "Convierte visitas y mensajes en oportunidades con contexto.", description: "Wesley combina sitio web, automatización de WhatsApp e IA para ayudar a tu empresa a explicar mejor su oferta, responder con más claridad y guiar cada contacto al siguiente paso.", primaryCta: "Ver mi diagnóstico gratuito", secondaryCta: "Entender el proceso", highlights: ["Sin compromiso de contratación", "Resumen antes de abrir WhatsApp"] },
  heroPanel: { eyebrow: "Lo que organiza el diagnóstico", items: ["Dónde entra hoy el lead", "Qué enfría la conversación", "El menor siguiente paso para probar", "Cómo Wesley recibe el contexto"], bottom: "Llegas a la conversación sin repetir todo desde cero." }, deliverables: ["Diagnóstico del principal obstáculo", "Dirección para sitio, WhatsApp o IA", "Resumen de conversación ya contextualizado"],
  solutions: { eyebrow: "Soluciones conectadas", title: "Más claridad en el mensaje. Menos fricción en el camino a la venta.", description: "Cada solución resuelve una parte del mismo recorrido: atraer a la persona adecuada, explicar la oferta y guiar el contacto con consistencia.", cards: [{ title: "Sitios que posicionan", text: "Páginas que explican tu solución, generan confianza y muestran claramente el siguiente paso." }, { title: "WhatsApp que organiza", text: "Flujos de atención para responder, calificar y transferir el contexto a tu equipo." }, { title: "IA con límites claros", text: "Automatización con temas aprobados, ruta humana y mejora continua según la operación." }] },
  friction: { eyebrow: "Donde Altixdev ayuda más", title: "No empieces por el código. Empieza por el obstáculo que está costando conversaciones.", description: "El diagnóstico es ideal para empresas que ya reciben interés, pero necesitan convertir el esfuerzo en una experiencia más clara para el lead y el equipo.", cta: "Identificar mi obstáculo", positiveTitle: "Buen momento para empezar", positiveItems: ["Tu empresa recibe contactos, pero pierde contexto.", "El sitio no deja clara la diferencia de tu solución.", "El equipo repite respuestas o tarda en responder.", "Quieres probar un flujo antes de un cambio mayor."], negativeTitle: "Lo que no prometemos", negativeItems: ["Automatización sin límites o responsable humano.", "Resultados garantizados sin entender la operación.", "Una propuesta genérica antes del diagnóstico.", "Contacto insistente después de pedir que paremos."] },
  process: { eyebrow: "Cómo funciona", title: "Wesley convierte la tecnología en un recorrido comercial más simple.", description: "No necesitas empezar con un proyecto gigante. Altixdev comienza entendiendo el objetivo, el obstáculo y el cambio más pequeño capaz de generar aprendizaje antes de ampliar la automatización.", steps: [{ title: "Descubrir", text: "Mapeamos objetivo, canal, obstáculo y urgencia." }, { title: "Diseñar", text: "Conectamos mensaje, sitio, WhatsApp y personas." }, { title: "Implementar", text: "Construimos con alcance, límites y responsables." }, { title: "Evolucionar", text: "Medimos, ajustamos y ampliamos lo que tiene sentido." }] },
  faq: { eyebrow: "Antes de empezar", title: "Preguntas frecuentes, respondidas con claridad.", items: [{ question: "¿El diagnóstico me obliga a contratar?", answer: "No. Sirve para organizar el contexto e indicar un camino de conversación. Tú decides si quieres continuar." }, { question: "¿Necesito tener ya un sitio o automatización?", answer: "No. El diagnóstico también ayuda a entender por dónde empezar y qué prioridad tiene más sentido." }, { question: "¿La IA sustituye toda la atención?", answer: "No. Altixdev trabaja con límites, temas aprobados y transferencia humana cuando el contexto requiere una persona." }, { question: "¿Qué ocurre después de enviar mis datos?", answer: "El lead se registra en el panel de Altixdev, el resumen se incluye en el mensaje de WhatsApp y Wesley puede continuar la conversación si lo autorizas." }] },
  diagnostic: { eyebrow: "Diagnóstico guiado", title: "Encuentra el siguiente paso más útil antes de pedir una propuesta.", description: "En cinco pasos, organizas el escenario. Al final, Wesley recibe un resumen de tu necesidad y WhatsApp se abre con la conversación preparada.", benefits: ["Eliges solo respuestas relevantes para tu contexto.", "El registro evita que tengas que explicar todo de nuevo.", "El contacto solo continúa si das tu consentimiento."], progress: "{{progress}}% completado", responseNotice: "Tu respuesta se usará solo para crear un resumen más útil para la conversación.", questionSteps: [{ eyebrow: "01 · Resultado deseado", title: "¿Qué quieres hacer más eficiente ahora?", options: ["Generar más oportunidades", "Convertir más contactos", "Reducir tareas manuales", "Organizar una operación digital"] }, { eyebrow: "02 · Canal actual", title: "¿Dónde comienzan hoy tus conversaciones y oportunidades?", options: ["Instagram", "WhatsApp", "Recomendación", "Sitio web", "Correo", "Otro"] }, { eyebrow: "03 · Principal obstáculo", title: "¿Qué punto frena más tu avance?", options: ["El sitio no explica bien la solución", "Los leads no reciben respuesta a tiempo", "La atención es muy repetitiva", "Falta proceso comercial"] }, { eyebrow: "04 · Momento de decisión", title: "¿Qué urgencia tiene resolverlo?", options: ["Quiero empezar en las próximas semanas", "Estoy comparando soluciones", "Quiero estructurar el plan primero", "Aún estoy entendiendo el problema"] }], contactEyebrow: "05 · Tus datos", contactTitle: "Envía el resumen a tu conversación de WhatsApp.", contactDescription: "Registramos el diagnóstico en el pipeline de Altixdev y abrimos WhatsApp con el contexto incluido.", fields: { name: "Nombre", namePlaceholder: "¿Cómo podemos llamarte?", company: "Empresa", companyPlaceholder: "Nombre de la empresa", email: "Correo electrónico", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "Autorizo a Altixdev a usar mis datos para responder mi solicitud, enviar este resumen y contactarme sobre esta oportunidad. Puedo solicitar que el contacto se detenga en cualquier momento.", privacyNotice: "Al continuar verás el mensaje con tus respuestas en WhatsApp. No hay propuestas automáticas ni inclusión en listas sin autorización.", back: "Volver", continue: "Continuar", submit: "Ver resumen y hablar por WhatsApp", submitting: "Guardando…" }, footerTagline: "Tecnología que prepara mejores conversaciones.", toasts: { chooseOption: "Elige una opción para continuar.", consent: "Confirma tu consentimiento para enviar el diagnóstico.", createLeadError: "No pudimos registrar tu diagnóstico. Revisa los datos e inténtalo de nuevo." }, whatsappIntro: "Hola, Wesley. He completado el diagnóstico de Altixdev y me gustaría conversar.",
};

const ptPT: SiteCopy = {
  ...ptBR,
  metaTitle: "Altixdev — Website, WhatsApp e IA com contexto",
  languageLabel: "Idioma da página",
  nav: { solutions: "Soluções", process: "Como funciona", diagnostic: "Diagnóstico", start: "Iniciar diagnóstico" },
  hero: { badge: "Diagnóstico gratuito em 5 etapas", title: "Transforme visitas e mensagens em oportunidades com contexto.", description: "Wesley combina website, automação de WhatsApp e IA para ajudar a sua empresa a explicar melhor a oferta, responder com mais clareza e conduzir cada contacto até ao próximo passo.", primaryCta: "Ver o meu diagnóstico gratuito", secondaryCta: "Compreender o processo", highlights: ["Sem compromisso de contratação", "Resumo antes de abrir o WhatsApp"] },
  heroPanel: { eyebrow: "O que o diagnóstico organiza", items: ["Onde o potencial cliente entra hoje", "Que ponto está a arrefecer a conversa", "O menor passo seguinte a testar", "Como Wesley recebe o contexto"], bottom: "Chega à conversa sem repetir tudo desde o início." },
  deliverables: ["Diagnóstico do principal bloqueio", "Orientação de website, WhatsApp ou IA", "Resumo da conversa já contextualizado"],
  solutions: { ...ptBR.solutions, title: "Mais clareza na mensagem. Menos fricção no caminho até à venda.", description: "Cada solução resolve uma parte da mesma jornada: atrair a pessoa certa, explicar a oferta e conduzir o contacto com consistência.", cards: [{ title: "Websites que posicionam", text: "Páginas que explicam a sua solução, criam confiança e mostram claramente o passo seguinte." }, { title: "WhatsApp que organiza", text: "Fluxos de atendimento para responder, qualificar e transferir o contexto para a sua equipa." }, { title: "IA com limites claros", text: "Automação com temas aprovados, rota humana e melhoria contínua conforme a operação." }] },
  friction: { ...ptBR.friction, title: "Não comece pelo código. Comece pelo bloqueio que está a custar conversas.", description: "O diagnóstico é indicado para empresas que já recebem algum interesse, mas precisam de transformar esforço numa experiência mais clara para o potencial cliente e para a equipa.", cta: "Identificar o meu bloqueio", positiveItems: ["A sua empresa recebe contactos, mas perde contexto.", "O website não torna clara a diferença da sua solução.", "A equipa repete respostas ou demora a responder.", "Quer testar um fluxo antes de uma mudança maior."] },
  process: { ...ptBR.process, title: "Wesley transforma tecnologia numa jornada comercial mais simples.", description: "Não precisa de começar com um projeto gigante. A Altixdev começa por compreender o objetivo, o bloqueio e a menor mudança capaz de gerar aprendizagem antes de ampliar qualquer automação.", steps: [{ title: "Descobrir", text: "Mapeamos objetivo, canal, bloqueio e urgência." }, { title: "Desenhar", text: "Ligamos mensagem, website, WhatsApp e pessoas." }, { title: "Implementar", text: "Construímos com âmbito, limites e responsáveis." }, { title: "Evoluir", text: "Medimos, ajustamos e ampliamos o que faz sentido." }] },
  faq: { ...ptBR.faq, items: [{ question: "O diagnóstico obriga-me a contratar?", answer: "Não. Serve para organizar o contexto e indicar um caminho de conversa. Decide se quer avançar depois." }, { question: "Preciso de já ter website ou automação?", answer: "Não. O diagnóstico também ajuda quando quer perceber por onde começar e qual a prioridade mais indicada." }, { question: "A IA substitui todo o atendimento?", answer: "Não. A Altixdev trabalha com limites, temas aprovados e encaminhamento humano quando o contexto pede uma pessoa." }, { question: "O que acontece depois de enviar os meus dados?", answer: "O potencial cliente é registado no painel da Altixdev, o resumo é incluído na mensagem de WhatsApp e Wesley pode continuar a conversa se autorizar." }] },
  diagnostic: { ...ptBR.diagnostic, title: "Encontre o passo seguinte mais útil antes de pedir uma proposta.", description: "Em cinco etapas, organiza o cenário. No final, Wesley recebe um resumo da necessidade e o WhatsApp abre com a conversa preparada.", benefits: ["Escolhe apenas respostas relevantes para o seu contexto.", "O registo evita que tenha de explicar tudo novamente.", "O contacto só continua se der consentimento no formulário."], progress: "{{progress}}% concluído", questionSteps: [{ eyebrow: "01 · Resultado pretendido", title: "O que quer tornar mais eficiente agora?", options: ["Gerar mais oportunidades", "Converter mais contactos", "Reduzir tarefas manuais", "Organizar uma operação digital"] }, { eyebrow: "02 · Canal atual", title: "Onde começam hoje as suas conversas e oportunidades?", options: ["Instagram", "WhatsApp", "Recomendação", "Website", "E-mail", "Outro"] }, { eyebrow: "03 · Principal bloqueio", title: "Que ponto mais trava o seu avanço?", options: ["O website não explica bem a solução", "Os potenciais clientes não recebem resposta a tempo", "O atendimento é muito repetitivo", "Falta processo comercial"] }, { eyebrow: "04 · Momento da decisão", title: "Qual é a urgência para resolver isto?", options: ["Quero começar nas próximas semanas", "Estou a comparar soluções", "Quero estruturar primeiro o plano", "Ainda estou a compreender o problema"] }], contactEyebrow: "05 · Os seus dados", contactTitle: "Envie o resumo para a sua conversa no WhatsApp.", contactDescription: "Registamos o diagnóstico no pipeline da Altixdev e abrimos o WhatsApp com o contexto incluído.", fields: { name: "Nome", namePlaceholder: "Como lhe podemos chamar?", company: "Empresa", companyPlaceholder: "Nome da empresa", email: "E-mail", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "Autorizo a Altixdev a usar os meus dados para responder ao meu pedido, enviar o resumo deste diagnóstico e fazer contacto sobre esta oportunidade. Posso pedir a interrupção do contacto a qualquer momento.", privacyNotice: "Ao continuar, verá a mensagem com as suas respostas no WhatsApp. Não há envio automático de propostas nem inclusão em listas sem autorização.", back: "Voltar", continue: "Continuar", submit: "Ver resumo e falar no WhatsApp", submitting: "A guardar…" },
  footerTagline: "Tecnologia que prepara conversas melhores.", toasts: { chooseOption: "Escolha uma opção para continuar.", consent: "Confirme o consentimento para enviar o diagnóstico.", createLeadError: "Não foi possível registar o diagnóstico. Reveja os dados e tente novamente." }, whatsappIntro: "Olá, Wesley. Concluí o diagnóstico da Altixdev e gostaria de conversar.",
};

const de: SiteCopy = {
  metaTitle: "Altixdev — Website, WhatsApp und KI mit Kontext", languageLabel: "Seitensprache", nav: { solutions: "Lösungen", process: "So funktioniert es", diagnostic: "Diagnose", start: "Diagnose starten" },
  hero: { badge: "Kostenlose Diagnose in 5 Schritten", title: "Machen Sie aus Besuchen und Nachrichten Chancen mit Kontext.", description: "Wesley verbindet Websites, WhatsApp-Automatisierung und KI, damit Ihr Unternehmen sein Angebot klarer erklärt, besser antwortet und jeden Kontakt zum nächsten Schritt führt.", primaryCta: "Meine kostenlose Diagnose", secondaryCta: "Prozess verstehen", highlights: ["Keine Beauftragung erforderlich", "Zusammenfassung vor dem Öffnen von WhatsApp"] },
  heroPanel: { eyebrow: "Was die Diagnose ordnet", items: ["Wo der Lead heute einsteigt", "Was das Gespräch abkühlt", "Der kleinste nächste Testschritt", "Wie Wesley den Kontext erhält"], bottom: "Sie kommen ins Gespräch, ohne alles von vorne zu wiederholen." }, deliverables: ["Diagnose des wichtigsten Engpasses", "Richtung für Website, WhatsApp oder KI", "Bereits kontextualisierte Gesprächszusammenfassung"],
  solutions: { eyebrow: "Vernetzte Lösungen", title: "Mehr Klarheit in der Botschaft. Weniger Reibung auf dem Weg zum Verkauf.", description: "Jede Lösung löst einen Teil derselben Reise: die richtige Person anziehen, das Angebot erklären und den Kontakt konsistent führen.", cards: [{ title: "Websites mit Positionierung", text: "Seiten, die Ihre Lösung erklären, Vertrauen schaffen und den nächsten Schritt klar zeigen." }, { title: "WhatsApp, der organisiert", text: "Abläufe zum Antworten, Qualifizieren und Übergeben des Kontexts an Ihr Team." }, { title: "KI mit klaren Grenzen", text: "Automatisierung mit freigegebenen Themen, menschlicher Route und kontinuierlicher Verbesserung." }] },
  friction: { eyebrow: "Wo Altixdev am meisten hilft", title: "Beginnen Sie nicht mit Code. Beginnen Sie mit dem Engpass, der Gespräche kostet.", description: "Die Diagnose ist ideal für Unternehmen, die bereits Interesse erhalten, aber daraus eine klarere Erfahrung für Leads und Team machen müssen.", cta: "Meinen Engpass erkennen", positiveTitle: "Ein guter Zeitpunkt zum Start", positiveItems: ["Ihr Unternehmen erhält Kontakte, verliert aber Kontext.", "Ihre Website macht den Unterschied Ihrer Lösung nicht klar.", "Das Team wiederholt Antworten oder reagiert zu spät.", "Sie möchten einen Ablauf vor einer größeren Änderung testen."], negativeTitle: "Was wir nicht versprechen", negativeItems: ["Automatisierung ohne Grenzen oder menschliche Verantwortung.", "Garantierte Ergebnisse ohne Verständnis der Abläufe.", "Ein allgemeines Angebot vor der Diagnose.", "Aufdringlichen Kontakt, nachdem Sie um einen Stopp gebeten haben."] },
  process: { eyebrow: "So funktioniert es", title: "Wesley macht aus Technologie eine einfachere Vertriebsreise.", description: "Sie müssen nicht mit einem riesigen Projekt beginnen. Altixdev versteht zuerst Ziel, Engpass und die kleinste Änderung mit Lernpotenzial, bevor Automatisierung erweitert wird.", steps: [{ title: "Entdecken", text: "Wir erfassen Ziel, Kanal, Engpass und Dringlichkeit." }, { title: "Gestalten", text: "Wir verbinden Botschaft, Website, WhatsApp und Menschen." }, { title: "Umsetzen", text: "Wir bauen mit Umfang, Grenzen und Verantwortlichen." }, { title: "Weiterentwickeln", text: "Wir messen, passen an und erweitern, was sinnvoll ist." }] },
  faq: { eyebrow: "Vor dem Start", title: "Häufige Fragen, klar beantwortet.", items: [{ question: "Verpflichtet mich die Diagnose zu einer Beauftragung?", answer: "Nein. Sie ordnet den Kontext und zeigt einen möglichen Gesprächsweg. Sie entscheiden, ob Sie fortfahren möchten." }, { question: "Brauche ich bereits eine Website oder Automatisierung?", answer: "Nein. Die Diagnose hilft auch dabei zu verstehen, wo Sie beginnen und welche Priorität sinnvoll ist." }, { question: "Ersetzt KI den gesamten Kundenservice?", answer: "Nein. Altixdev arbeitet mit Grenzen, freigegebenen Themen und menschlicher Übergabe, wenn der Kontext eine Person erfordert." }, { question: "Was passiert nach dem Senden meiner Daten?", answer: "Der Lead wird im Altixdev-Panel registriert, die Zusammenfassung wird in die WhatsApp-Nachricht aufgenommen und Wesley kann das Gespräch mit Ihrer Zustimmung fortsetzen." }] },
  diagnostic: { eyebrow: "Geführte Diagnose", title: "Finden Sie den sinnvollsten nächsten Schritt, bevor Sie ein Angebot anfordern.", description: "In fünf Schritten ordnen Sie die Situation. Am Ende erhält Wesley eine Zusammenfassung und WhatsApp öffnet sich mit vorbereitetem Gespräch.", benefits: ["Sie wählen nur Antworten, die zu Ihrem Kontext passen.", "Die Aufzeichnung verhindert, dass Sie alles erneut erklären müssen.", "Der Kontakt wird nur mit Ihrer Einwilligung fortgesetzt."], progress: "{{progress}}% abgeschlossen", responseNotice: "Ihre Antwort wird nur verwendet, um eine nützlichere Gesprächszusammenfassung zu erstellen.", questionSteps: [{ eyebrow: "01 · Gewünschtes Ergebnis", title: "Was möchten Sie jetzt effizienter machen?", options: ["Mehr Chancen schaffen", "Mehr Kontakte umwandeln", "Manuelle Aufgaben reduzieren", "Einen digitalen Ablauf organisieren"] }, { eyebrow: "02 · Aktueller Kanal", title: "Wo beginnen Ihre Gespräche und Chancen heute?", options: ["Instagram", "WhatsApp", "Empfehlung", "Website", "E-Mail", "Anderes"] }, { eyebrow: "03 · Wichtigster Engpass", title: "Welcher Punkt bremst Ihren Fortschritt am meisten?", options: ["Die Website erklärt die Lösung nicht gut", "Leads erhalten nicht rechtzeitig eine Antwort", "Der Service ist zu wiederholend", "Ein Vertriebsprozess fehlt"] }, { eyebrow: "04 · Entscheidungszeitpunkt", title: "Wie dringend ist die Lösung?", options: ["Ich möchte in den nächsten Wochen beginnen", "Ich vergleiche Lösungen", "Ich möchte zuerst den Plan strukturieren", "Ich verstehe das Problem noch"] }], contactEyebrow: "05 · Ihre Daten", contactTitle: "Senden Sie die Zusammenfassung an Ihr WhatsApp-Gespräch.", contactDescription: "Wir registrieren die Diagnose in der Altixdev-Pipeline und öffnen WhatsApp mit dem Kontext.", fields: { name: "Name", namePlaceholder: "Wie dürfen wir Sie nennen?", company: "Unternehmen", companyPlaceholder: "Name des Unternehmens", email: "E-Mail", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "Ich ermächtige Altixdev, meine Daten zu verwenden, um meine Anfrage zu beantworten, diese Diagnosezusammenfassung zu senden und mich zu dieser Gelegenheit zu kontaktieren. Ich kann die Kontaktaufnahme jederzeit stoppen lassen.", privacyNotice: "Wenn Sie fortfahren, sehen Sie die Nachricht mit Ihren Antworten in WhatsApp. Es gibt keine automatischen Angebote oder Listenanmeldungen ohne Zustimmung.", back: "Zurück", continue: "Weiter", submit: "Zusammenfassung ansehen und über WhatsApp sprechen", submitting: "Speichern…" }, footerTagline: "Technologie für bessere Gespräche.", toasts: { chooseOption: "Wählen Sie eine Option, um fortzufahren.", consent: "Bestätigen Sie Ihre Einwilligung, um die Diagnose zu senden.", createLeadError: "Ihre Diagnose konnte nicht registriert werden. Prüfen Sie die Daten und versuchen Sie es erneut." }, whatsappIntro: "Hallo Wesley! Ich habe die Altixdev-Diagnose abgeschlossen und möchte sprechen.",
};

const nl: SiteCopy = {
  metaTitle: "Altixdev — Website, WhatsApp en AI met context", languageLabel: "Paginataal", nav: { solutions: "Oplossingen", process: "Hoe het werkt", diagnostic: "Diagnose", start: "Diagnose starten" },
  hero: { badge: "Gratis diagnose in 5 stappen", title: "Maak van bezoeken en berichten kansen met context.", description: "Wesley combineert websites, WhatsApp-automatisering en AI om uw bedrijf te helpen het aanbod beter uit te leggen, duidelijker te reageren en elk contact naar de volgende stap te begeleiden.", primaryCta: "Mijn gratis diagnose", secondaryCta: "Het proces begrijpen", highlights: ["Geen verplichting tot afname", "Samenvatting vóór WhatsApp opent"] },
  heroPanel: { eyebrow: "Wat de diagnose organiseert", items: ["Waar de lead vandaag binnenkomt", "Welk punt het gesprek afkoelt", "De kleinste volgende stap om te testen", "Hoe Wesley de context ontvangt"], bottom: "U komt in het gesprek zonder alles opnieuw uit te leggen." }, deliverables: ["Diagnose van het belangrijkste knelpunt", "Richting voor website, WhatsApp of AI", "Gesprekssamenvatting met context"],
  solutions: { eyebrow: "Verbonden oplossingen", title: "Meer duidelijkheid in de boodschap. Minder frictie op weg naar verkoop.", description: "Elke oplossing lost een deel van dezelfde reis op: de juiste persoon aantrekken, het aanbod uitleggen en contact consistent begeleiden.", cards: [{ title: "Websites die positioneren", text: "Pagina's die uw oplossing uitleggen, vertrouwen opbouwen en de volgende stap helder tonen." }, { title: "WhatsApp die organiseert", text: "Serviceflows om te antwoorden, te kwalificeren en context aan uw team over te dragen." }, { title: "AI met duidelijke grenzen", text: "Automatisering met goedgekeurde onderwerpen, een menselijke route en continue verbetering." }] },
  friction: { eyebrow: "Waar Altixdev het meest helpt", title: "Begin niet met code. Begin met het knelpunt dat gesprekken kost.", description: "De diagnose is ideaal voor bedrijven die al interesse ontvangen maar inspanning moeten omzetten in een duidelijkere ervaring voor lead en team.", cta: "Mijn knelpunt herkennen", positiveTitle: "Een goed moment om te starten", positiveItems: ["Uw bedrijf ontvangt contacten maar verliest context.", "Uw website maakt het verschil van uw oplossing niet duidelijk.", "Het team herhaalt antwoorden of reageert te laat.", "U wilt een flow testen vóór een grotere verandering."], negativeTitle: "Wat we niet beloven", negativeItems: ["Automatisering zonder grenzen of menselijke eigenaar.", "Gegarandeerde resultaten zonder de operatie te begrijpen.", "Een generiek voorstel vóór de diagnose.", "Aanhoudend contact nadat u vraagt te stoppen."] },
  process: { eyebrow: "Hoe het werkt", title: "Wesley maakt van technologie een eenvoudiger commercieel traject.", description: "U hoeft niet met een enorm project te beginnen. Altixdev begrijpt eerst doel, knelpunt en de kleinste verandering die kan leren voordat automatisering wordt uitgebreid.", steps: [{ title: "Ontdekken", text: "We brengen doel, kanaal, knelpunt en urgentie in kaart." }, { title: "Ontwerpen", text: "We verbinden boodschap, website, WhatsApp en mensen." }, { title: "Implementeren", text: "We bouwen met scope, grenzen en verantwoordelijken." }, { title: "Ontwikkelen", text: "We meten, passen aan en breiden uit wat zinvol is." }] },
  faq: { eyebrow: "Voor u begint", title: "Veelgestelde vragen, helder beantwoord.", items: [{ question: "Verplicht de diagnose mij om iets af te nemen?", answer: "Nee. De diagnose ordent de context en wijst een mogelijk gesprekspad aan. U beslist of u verder wilt." }, { question: "Heb ik al een website of automatisering nodig?", answer: "Nee. De diagnose helpt ook wanneer u wilt begrijpen waar te starten en welke prioriteit zinvol is." }, { question: "Vervangt AI alle klantenservice?", answer: "Nee. Altixdev werkt met grenzen, goedgekeurde onderwerpen en menselijke overdracht wanneer de context een persoon vraagt." }, { question: "Wat gebeurt er nadat ik mijn gegevens verstuur?", answer: "De lead wordt in het Altixdev-panel geregistreerd, de samenvatting wordt toegevoegd aan het WhatsApp-bericht en Wesley kan het gesprek voortzetten als u dat toestaat." }] },
  diagnostic: { eyebrow: "Begeleide diagnose", title: "Vind de nuttigste volgende stap voordat u om een voorstel vraagt.", description: "In vijf stappen organiseert u de situatie. Aan het einde ontvangt Wesley een samenvatting en opent WhatsApp met het gesprek voorbereid.", benefits: ["U kiest alleen antwoorden die relevant zijn voor uw context.", "De registratie voorkomt dat u alles opnieuw moet uitleggen.", "Contact gaat alleen verder met uw toestemming."], progress: "{{progress}}% voltooid", responseNotice: "Uw antwoord wordt alleen gebruikt om een nuttigere samenvatting voor het gesprek te maken.", questionSteps: [{ eyebrow: "01 · Gewenst resultaat", title: "Wat wilt u nu efficiënter maken?", options: ["Meer kansen genereren", "Meer contacten converteren", "Handmatige taken verminderen", "Een digitale operatie organiseren"] }, { eyebrow: "02 · Huidig kanaal", title: "Waar beginnen uw gesprekken en kansen vandaag?", options: ["Instagram", "WhatsApp", "Verwijzing", "Website", "E-mail", "Anders"] }, { eyebrow: "03 · Belangrijkste knelpunt", title: "Welk punt remt uw vooruitgang het meest?", options: ["De website legt de oplossing niet goed uit", "Leads krijgen niet op tijd antwoord", "De service is te repetitief", "Er ontbreekt een commercieel proces"] }, { eyebrow: "04 · Beslismoment", title: "Hoe urgent is het om dit op te lossen?", options: ["Ik wil de komende weken beginnen", "Ik vergelijk oplossingen", "Ik wil eerst het plan structureren", "Ik begrijp het probleem nog"] }], contactEyebrow: "05 · Uw gegevens", contactTitle: "Stuur de samenvatting naar uw WhatsApp-gesprek.", contactDescription: "We registreren de diagnose in de Altixdev-pipeline en openen WhatsApp met de context.", fields: { name: "Naam", namePlaceholder: "Hoe mogen we u noemen?", company: "Bedrijf", companyPlaceholder: "Bedrijfsnaam", email: "E-mail", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "Ik geef Altixdev toestemming om mijn gegevens te gebruiken om mijn verzoek te beantwoorden, deze diagnoseschatting te sturen en contact op te nemen over deze kans. Ik kan op elk moment vragen om contact te stoppen.", privacyNotice: "Door verder te gaan ziet u het bericht met uw antwoorden in WhatsApp. Er zijn geen automatische voorstellen of lijstinschrijvingen zonder toestemming.", back: "Terug", continue: "Doorgaan", submit: "Samenvatting bekijken en praten via WhatsApp", submitting: "Opslaan…" }, footerTagline: "Technologie die betere gesprekken voorbereidt.", toasts: { chooseOption: "Kies een optie om door te gaan.", consent: "Bevestig uw toestemming om de diagnose te versturen.", createLeadError: "We konden uw diagnose niet registreren. Controleer de gegevens en probeer opnieuw." }, whatsappIntro: "Hallo Wesley! Ik heb de Altixdev-diagnose afgerond en wil graag praten.",
};

const ru: SiteCopy = {
  metaTitle: "Altixdev — Сайт, WhatsApp и ИИ с контекстом", languageLabel: "Язык страницы", nav: { solutions: "Решения", process: "Как это работает", diagnostic: "Диагностика", start: "Начать диагностику" },
  hero: { badge: "Бесплатная диагностика в 5 шагах", title: "Превратите посещения и сообщения в возможности с контекстом.", description: "Wesley объединяет сайты, автоматизацию WhatsApp и ИИ, чтобы помочь вашей компании лучше объяснять предложение, яснее отвечать и вести каждый контакт к следующему шагу.", primaryCta: "Получить бесплатную диагностику", secondaryCta: "Понять процесс", highlights: ["Без обязательств", "Резюме до открытия WhatsApp"] },
  heroPanel: { eyebrow: "Что упорядочивает диагностика", items: ["Где лид появляется сегодня", "Что охлаждает разговор", "Минимальный следующий шаг для проверки", "Как Wesley получает контекст"], bottom: "Вы переходите к разговору, не повторяя всё с самого начала." }, deliverables: ["Диагностика главного узкого места", "Направление для сайта, WhatsApp или ИИ", "Резюме разговора с контекстом"],
  solutions: { eyebrow: "Связанные решения", title: "Больше ясности в сообщении. Меньше трения на пути к продаже.", description: "Каждое решение закрывает часть одного пути: привлечь нужного человека, объяснить предложение и последовательно вести контакт.", cards: [{ title: "Сайты, которые позиционируют", text: "Страницы, объясняющие ваше решение, создающие доверие и ясно показывающие следующий шаг." }, { title: "WhatsApp, который организует", text: "Сценарии обслуживания для ответа, квалификации и передачи контекста вашей команде." }, { title: "ИИ с ясными границами", text: "Автоматизация с одобренными темами, человеческим маршрутом и постоянным улучшением." }] },
  friction: { eyebrow: "Где Altixdev помогает больше всего", title: "Не начинайте с кода. Начните с узкого места, которое стоит вам разговоров.", description: "Диагностика идеальна для компаний, уже получающих интерес, но нуждающихся в более понятном опыте для лида и команды.", cta: "Определить моё узкое место", positiveTitle: "Хороший момент для старта", positiveItems: ["Ваша компания получает контакты, но теряет контекст.", "Сайт не показывает отличие вашего решения.", "Команда повторяет ответы или отвечает слишком долго.", "Вы хотите проверить сценарий до большого изменения."], negativeTitle: "Чего мы не обещаем", negativeItems: ["Автоматизацию без ограничений или ответственного человека.", "Гарантированный результат без понимания операций.", "Общее предложение до диагностики.", "Настойчивые контакты после просьбы остановиться."] },
  process: { eyebrow: "Как это работает", title: "Wesley превращает технологии в более простой коммерческий путь.", description: "Вам не нужно начинать с огромного проекта. Altixdev сначала понимает цель, узкое место и минимальное изменение, которое даст обучение, до расширения автоматизации.", steps: [{ title: "Изучить", text: "Мы определяем цель, канал, узкое место и срочность." }, { title: "Спроектировать", text: "Мы соединяем сообщение, сайт, WhatsApp и людей." }, { title: "Внедрить", text: "Мы строим с объёмом, границами и ответственными." }, { title: "Развивать", text: "Мы измеряем, корректируем и расширяем то, что имеет смысл." }] },
  faq: { eyebrow: "Перед началом", title: "Частые вопросы — с ясными ответами.", items: [{ question: "Диагностика обязывает меня заказать услугу?", answer: "Нет. Она упорядочивает контекст и предлагает путь разговора. Вы решаете, двигаться ли дальше." }, { question: "Мне уже нужен сайт или автоматизация?", answer: "Нет. Диагностика полезна и когда вы хотите понять, с чего начать и какой приоритет важнее." }, { question: "ИИ заменяет всё обслуживание?", answer: "Нет. Altixdev работает с границами, одобренными темами и передачей человеку, когда контекст этого требует." }, { question: "Что произойдёт после отправки данных?", answer: "Лид регистрируется в панели Altixdev, резюме включается в сообщение WhatsApp, и Wesley может продолжить разговор с вашего разрешения." }] },
  diagnostic: { eyebrow: "Пошаговая диагностика", title: "Найдите самый полезный следующий шаг до запроса предложения.", description: "За пять шагов вы организуете ситуацию. В конце Wesley получает резюме, а WhatsApp открывается с подготовленным разговором.", benefits: ["Вы выбираете только ответы, важные для вашего контекста.", "Запись избавляет от необходимости объяснять всё снова.", "Контакт продолжается только с вашим согласием."], progress: "{{progress}}% завершено", responseNotice: "Ваш ответ будет использован только для более полезного резюме разговора.", questionSteps: [{ eyebrow: "01 · Желаемый результат", title: "Что вы хотите сделать эффективнее сейчас?", options: ["Создавать больше возможностей", "Конвертировать больше контактов", "Сократить ручные задачи", "Организовать цифровую операцию"] }, { eyebrow: "02 · Текущий канал", title: "Где сегодня начинаются ваши разговоры и возможности?", options: ["Instagram", "WhatsApp", "Рекомендация", "Сайт", "Электронная почта", "Другое"] }, { eyebrow: "03 · Главное узкое место", title: "Какой пункт сильнее всего замедляет вас?", options: ["Сайт плохо объясняет решение", "Лиды не получают ответ вовремя", "Обслуживание слишком повторяется", "Нет коммерческого процесса"] }, { eyebrow: "04 · Момент решения", title: "Насколько срочно это решить?", options: ["Хочу начать в ближайшие недели", "Сравниваю решения", "Сначала хочу структурировать план", "Пока изучаю проблему"] }], contactEyebrow: "05 · Ваши данные", contactTitle: "Отправьте резюме в ваш разговор WhatsApp.", contactDescription: "Мы регистрируем диагностику в воронке Altixdev и открываем WhatsApp с контекстом.", fields: { name: "Имя", namePlaceholder: "Как к вам обращаться?", company: "Компания", companyPlaceholder: "Название компании", email: "Электронная почта", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "Я разрешаю Altixdev использовать мои данные, чтобы ответить на запрос, отправить это резюме диагностики и связаться со мной по этой возможности. Я могу в любой момент попросить прекратить контакт.", privacyNotice: "Продолжая, вы увидите сообщение с вашими ответами в WhatsApp. Автоматических предложений или подписок без разрешения нет.", back: "Назад", continue: "Продолжить", submit: "Посмотреть резюме и поговорить в WhatsApp", submitting: "Сохранение…" }, footerTagline: "Технологии, которые готовят лучшие разговоры.", toasts: { chooseOption: "Выберите вариант, чтобы продолжить.", consent: "Подтвердите согласие на отправку диагностики.", createLeadError: "Не удалось зарегистрировать диагностику. Проверьте данные и попробуйте снова." }, whatsappIntro: "Здравствуйте, Wesley! Я завершил диагностику Altixdev и хотел бы поговорить.",
};

const nb: SiteCopy = {
  metaTitle: "Altixdev — Nettside, WhatsApp og KI med kontekst", languageLabel: "Språk på siden", nav: { solutions: "Løsninger", process: "Slik fungerer det", diagnostic: "Diagnose", start: "Start diagnose" },
  hero: { badge: "Gratis diagnose i 5 trinn", title: "Gjør besøk og meldinger om til muligheter med kontekst.", description: "Wesley kombinerer nettsider, WhatsApp-automatisering og KI for å hjelpe bedriften din med å forklare tilbudet bedre, svare tydeligere og lede hver kontakt til neste steg.", primaryCta: "Få min gratis diagnose", secondaryCta: "Forstå prosessen", highlights: ["Ingen forpliktelse", "Sammendrag før WhatsApp åpnes"] },
  heroPanel: { eyebrow: "Hva diagnosen organiserer", items: ["Hvor leadden kommer inn i dag", "Hva som kjøler ned samtalen", "Det minste neste steget å teste", "Hvordan Wesley mottar konteksten"], bottom: "Du kommer til samtalen uten å gjenta alt fra bunnen av." }, deliverables: ["Diagnose av hovedflaskehalsen", "Retning for nettside, WhatsApp eller KI", "Samtalesammendrag med kontekst"],
  solutions: { eyebrow: "Sammenkoblede løsninger", title: "Mer klarhet i budskapet. Mindre friksjon på veien til salg.", description: "Hver løsning løser en del av den samme reisen: tiltrekke riktig person, forklare tilbudet og lede kontakten konsekvent.", cards: [{ title: "Nettsider som posisjonerer", text: "Sider som forklarer løsningen din, bygger tillit og tydelig viser neste steg." }, { title: "WhatsApp som organiserer", text: "Serviceflyter for å svare, kvalifisere og overføre kontekst til teamet ditt." }, { title: "KI med klare grenser", text: "Automatisering med godkjente temaer, menneskelig rute og kontinuerlig forbedring." }] },
  friction: { eyebrow: "Der Altixdev hjelper mest", title: "Ikke start med kode. Start med flaskehalsen som koster samtaler.", description: "Diagnosen er ideell for bedrifter som allerede får interesse, men må gjøre innsatsen om til en klarere opplevelse for lead og team.", cta: "Identifiser min flaskehals", positiveTitle: "Et godt tidspunkt å starte", positiveItems: ["Bedriften din får kontakter, men mister kontekst.", "Nettsiden viser ikke tydelig forskjellen i løsningen din.", "Teamet gjentar svar eller bruker for lang tid på å svare.", "Du vil teste en flyt før en større endring."], negativeTitle: "Det vi ikke lover", negativeItems: ["Automatisering uten grenser eller menneskelig ansvar.", "Garanterte resultater uten å forstå driften.", "Et generisk forslag før diagnosen.", "Vedvarende kontakt etter at du ber oss stoppe."] },
  process: { eyebrow: "Slik fungerer det", title: "Wesley gjør teknologi til en enklere kommersiell reise.", description: "Du trenger ikke starte med et enormt prosjekt. Altixdev forstår først mål, flaskehals og den minste endringen som kan gi læring før automatisering utvides.", steps: [{ title: "Oppdage", text: "Vi kartlegger mål, kanal, flaskehals og hast." }, { title: "Utforme", text: "Vi kobler budskap, nettside, WhatsApp og mennesker." }, { title: "Implementere", text: "Vi bygger med omfang, grenser og ansvarlige." }, { title: "Utvikle", text: "Vi måler, justerer og utvider det som gir mening." }] },
  faq: { eyebrow: "Før du starter", title: "Vanlige spørsmål, klart besvart.", items: [{ question: "Forplikter diagnosen meg til å kjøpe?", answer: "Nei. Den organiserer konteksten og peker på en samtalevei. Du bestemmer om du vil gå videre." }, { question: "Må jeg allerede ha en nettside eller automasjon?", answer: "Nei. Diagnosen hjelper også når du vil forstå hvor du skal starte og hvilken prioritet som gir mening." }, { question: "Erstatter KI all kundeservice?", answer: "Nei. Altixdev arbeider med grenser, godkjente temaer og menneskelig overføring når konteksten krever en person." }, { question: "Hva skjer etter at jeg sender opplysningene mine?", answer: "Leadden registreres i Altixdev-panelet, sammendraget legges i WhatsApp-meldingen og Wesley kan fortsette samtalen hvis du godkjenner det." }] },
  diagnostic: { eyebrow: "Veiledet diagnose", title: "Finn det mest nyttige neste steget før du ber om et tilbud.", description: "På fem steg organiserer du situasjonen. Til slutt mottar Wesley et sammendrag og WhatsApp åpnes med samtalen klar.", benefits: ["Du velger bare svar som er relevante for din kontekst.", "Registreringen gjør at du slipper å forklare alt på nytt.", "Kontakten fortsetter bare hvis du samtykker."], progress: "{{progress}}% fullført", responseNotice: "Svaret ditt brukes bare til å lage et nyttigere sammendrag for samtalen.", questionSteps: [{ eyebrow: "01 · Ønsket resultat", title: "Hva ønsker du å gjøre mer effektivt nå?", options: ["Skape flere muligheter", "Konvertere flere kontakter", "Redusere manuelle oppgaver", "Organisere en digital operasjon"] }, { eyebrow: "02 · Nåværende kanal", title: "Hvor starter samtalene og mulighetene dine i dag?", options: ["Instagram", "WhatsApp", "Anbefaling", "Nettside", "E-post", "Annet"] }, { eyebrow: "03 · Hovedflaskehals", title: "Hvilket punkt bremser fremgangen din mest?", options: ["Nettsiden forklarer ikke løsningen godt", "Leads får ikke svar i tide", "Servicen er for repeterende", "Det mangler en salgsprosess"] }, { eyebrow: "04 · Beslutningstidspunkt", title: "Hvor viktig haster det å løse dette?", options: ["Jeg vil starte de neste ukene", "Jeg sammenligner løsninger", "Jeg vil strukturere planen først", "Jeg forstår fortsatt problemet"] }], contactEyebrow: "05 · Dine opplysninger", contactTitle: "Send sammendraget til WhatsApp-samtalen din.", contactDescription: "Vi registrerer diagnosen i Altixdev-pipelinen og åpner WhatsApp med konteksten.", fields: { name: "Navn", namePlaceholder: "Hva kan vi kalle deg?", company: "Bedrift", companyPlaceholder: "Bedriftsnavn", email: "E-post", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "Jeg gir Altixdev tillatelse til å bruke opplysningene mine for å svare på forespørselen, sende dette diagnosesammendraget og kontakte meg om denne muligheten. Jeg kan når som helst be om at kontakten stopper.", privacyNotice: "Når du fortsetter, ser du meldingen med svarene dine i WhatsApp. Det finnes ingen automatiske tilbud eller listetillegg uten godkjenning.", back: "Tilbake", continue: "Fortsett", submit: "Se sammendrag og snakk på WhatsApp", submitting: "Lagrer…" }, footerTagline: "Teknologi som forbereder bedre samtaler.", toasts: { chooseOption: "Velg et alternativ for å fortsette.", consent: "Bekreft samtykket ditt for å sende diagnosen.", createLeadError: "Vi kunne ikke registrere diagnosen din. Kontroller opplysningene og prøv igjen." }, whatsappIntro: "Hei, Wesley! Jeg har fullført Altixdev-diagnosen og ønsker å snakke.",
};

const ga: SiteCopy = {
  metaTitle: "Altixdev — Suíomh, WhatsApp agus IS le comhthéacs", languageLabel: "Teanga an leathanaigh", nav: { solutions: "Réitigh", process: "Conas a oibríonn sé", diagnostic: "Diagnóis", start: "Tosaigh diagnóis" },
  hero: { badge: "Diagnóis saor in aisce i 5 chéim", title: "Déan deiseanna de chuairteanna agus de theachtaireachtaí le comhthéacs.", description: "Comhcheanglaíonn Wesley suíomhanna gréasáin, uathoibriú WhatsApp agus IS chun cabhrú le do ghnó an tairiscint a mhíniú níos fearr, freagairt níos soiléire agus gach teagmháil a threorú chuig an gcéad chéim eile.", primaryCta: "Faigh mo dhiagnóis saor in aisce", secondaryCta: "Tuig an próiseas", highlights: ["Gan oibleagáid conartha", "Achoimre sula n-osclaítear WhatsApp"] },
  heroPanel: { eyebrow: "An méid a eagraíonn an diagnóis", items: ["An áit a dtéann an treoraí isteach inniu", "An pointe a fhuaraíonn an comhrá", "An chéad chéim is lú le tástáil", "Mar a fhaigheann Wesley an comhthéacs"], bottom: "Sroicheann tú an comhrá gan gach rud a athrá ón tús." }, deliverables: ["Diagnóis ar an bpríomhbhac", "Treo don suíomh, WhatsApp nó IS", "Achoimre chomhthéacsaithe ar an gcomhrá"],
  solutions: { eyebrow: "Réitigh cheangailte", title: "Níos mó soiléireachta sa teachtaireacht. Níos lú frithchuimilte ar an mbealach chun díola.", description: "Réitíonn gach réiteach cuid den turas céanna: an duine ceart a mhealladh, an tairiscint a mhíniú agus an teagmháil a threorú go comhsheasmhach.", cards: [{ title: "Suíomhanna a shuíonn tú", text: "Leathanaigh a mhíníonn do réiteach, a chruthaíonn muinín agus a léiríonn an chéad chéim eile go soiléir." }, { title: "WhatsApp a eagraíonn", text: "Sreafaí seirbhíse chun freagairt, cáilithe agus comhthéacs a aistriú chuig d'fhoireann." }, { title: "IS le teorainneacha soiléire", text: "Uathoibriú le hábhair cheadaithe, bealach daonna agus feabhsú leanúnach." }] },
  friction: { eyebrow: "An áit a gcabhraíonn Altixdev is mó", title: "Ná tosaigh le cód. Tosaigh leis an mbac atá ag costas comhráite.", description: "Tá an diagnóis oiriúnach do ghnólachtaí a fhaigheann suim cheana féin ach a dteastaíonn eispéireas níos soiléire uathu don treoraí agus don fhoireann.", cta: "Sainaithin mo bhac", positiveTitle: "Dea-am le tosú", positiveItems: ["Faigheann do ghnó teagmhálaithe ach cailleann sé comhthéacs.", "Ní léiríonn do shuíomh difríocht do réitigh go soiléir.", "Déanann an fhoireann freagraí a athdhéanamh nó tógann sé rófhada freagairt.", "Ba mhaith leat sreabhadh a thástáil roimh athrú níos mó."], negativeTitle: "An méid nach ngeallaimid", negativeItems: ["Uathoibriú gan teorainneacha ná freagracht dhaonna.", "Torthaí ráthaithe gan oibriú a thuiscint.", "Togra ginearálta roimh an diagnóis.", "Teagmháil leanúnach tar éis duit iarraidh orainn stopadh."] },
  process: { eyebrow: "Conas a oibríonn sé", title: "Déanann Wesley turas tráchtála níos simplí den teicneolaíocht.", description: "Ní gá duit tosú le tionscadal ollmhór. Tuigeann Altixdev an sprioc, an bac agus an t-athrú is lú a chruthaíonn foghlaim sula leathnaítear uathoibriú.", steps: [{ title: "Faigh amach", text: "Mapálaimid sprioc, cainéal, bac agus práinn." }, { title: "Dear", text: "Ceanglaímid teachtaireacht, suíomh, WhatsApp agus daoine." }, { title: "Cuir i bhfeidhm", text: "Tógaimid le scóip, teorainneacha agus daoine freagracha." }, { title: "Forbair", text: "Tomhaisimid, coigeartaímid agus leathnaímid an méid atá ciallmhar." }] },
  faq: { eyebrow: "Sula dtosaíonn tú", title: "Ceisteanna coitianta, freagartha go soiléir.", items: [{ question: "An gcuireann an diagnóis iallach orm conradh a dhéanamh?", answer: "Ní chuireann. Eagraíonn sí an comhthéacs agus léiríonn sí bealach comhrá. Is tusa a shocraíonn ar mhaith leat dul ar aghaidh." }, { question: "An gá suíomh nó uathoibriú a bheith agam cheana?", answer: "Ní gá. Cuidíonn an diagnóis freisin nuair is mian leat tuiscint a fháil ar cá háit le tosú agus cén tosaíocht atá ciallmhar." }, { question: "An gcuireann IS an tseirbhís ar fad in ionad daoine?", answer: "Ní chuireann. Oibríonn Altixdev le teorainneacha, ábhair cheadaithe agus aistriú daonna nuair is gá duine." }, { question: "Cad a tharlaíonn i ndiaidh dom mo shonraí a sheoladh?", answer: "Cláraítear an treoraí sa phainéal Altixdev, cuirtear an achoimre sa teachtaireacht WhatsApp agus is féidir le Wesley an comhrá a leanúint le do chead." }] },
  diagnostic: { eyebrow: "Diagnóis threoraithe", title: "Faigh an chéad chéim eile is úsáidí sula n-iarrann tú togra.", description: "I gcúig chéim, eagraíonn tú an cás. Sa deireadh faigheann Wesley achoimre ar do riachtanas agus osclaítear WhatsApp leis an gcomhrá réidh.", benefits: ["Roghnaíonn tú freagraí atá ábhartha do do chomhthéacs amháin.", "Seachnaíonn an taifead go gcaithfidh tú gach rud a mhíniú arís.", "Ní leanann an teagmháil ach le do thoiliú."], progress: "{{progress}}% críochnaithe", responseNotice: "Ní úsáidfear do fhreagra ach chun achoimre níos úsáidí a chruthú don chomhrá.", questionSteps: [{ eyebrow: "01 · Toradh inmhianaithe", title: "Cad ba mhaith leat a dhéanamh níos éifeachtaí anois?", options: ["Níos mó deiseanna a ghiniúint", "Níos mó teagmhálaithe a thiontú", "Tascanna láimhe a laghdú", "Oibríocht dhigiteach a eagrú"] }, { eyebrow: "02 · Cainéal reatha", title: "Cén áit a dtosaíonn do chomhráite agus deiseanna inniu?", options: ["Instagram", "WhatsApp", "Atreorú", "Suíomh", "Ríomhphost", "Eile"] }, { eyebrow: "03 · Príomhbhac", title: "Cén pointe a chuireann moill is mó ar do dhul chun cinn?", options: ["Ní mhíníonn an suíomh an réiteach go maith", "Ní fhaigheann treoraithe freagra in am", "Tá an tseirbhís ró-athchleachtach", "Níl próiseas tráchtála ann"] }, { eyebrow: "04 · Am an chinnidh", title: "Cé chomh práinneach is atá sé é seo a réiteach?", options: ["Ba mhaith liom tosú sna seachtainí romhainn", "Táim ag comparáid réiteach", "Ba mhaith liom an plean a eagrú ar dtús", "Táim fós ag tuiscint na faidhbe"] }], contactEyebrow: "05 · Do shonraí", contactTitle: "Seol an achoimre chuig do chomhrá WhatsApp.", contactDescription: "Cláraímid an diagnóis i bpíblíne Altixdev agus osclaímid WhatsApp leis an gcomhthéacs.", fields: { name: "Ainm", namePlaceholder: "Cad is féidir linn a thabhairt ort?", company: "Gnólacht", companyPlaceholder: "Ainm an ghnólachta", email: "Ríomhphost", phone: "WhatsApp", phonePlaceholder: "+00 000 000 000" }, consent: "Tugaim cead do Altixdev mo shonraí a úsáid chun freagra a thabhairt ar m'iarratas, an achoimre diagnóise seo a sheoladh agus teagmháil a dhéanamh liom faoin deis seo. Is féidir liom iarraidh go stopfar an teagmháil am ar bith.", privacyNotice: "Nuair a leanann tú ar aghaidh, feicfidh tú an teachtaireacht le do fhreagraí i WhatsApp. Níl tograí uathoibríocha ná liostaí gan chead.", back: "Ar ais", continue: "Lean ar aghaidh", submit: "Féach ar an achoimre agus labhair ar WhatsApp", submitting: "Ag sábháil…" }, footerTagline: "Teicneolaíocht a ullmhaíonn comhráite níos fearr.", toasts: { chooseOption: "Roghnaigh rogha chun leanúint ar aghaidh.", consent: "Deimhnigh do thoiliú chun an diagnóis a sheoladh.", createLeadError: "Níorbh fhéidir do dhiagnóis a chlárú. Seiceáil na sonraí agus bain triail eile as." }, whatsappIntro: "Dia duit, Wesley! Chríochnaigh mé diagnóis Altixdev agus ba mhaith liom labhairt.",
};

const enGB: SiteCopy = {
  ...enUS,
  metaTitle: "Altixdev — Website, WhatsApp and AI with context",
  nav: { solutions: "Solutions", process: "How it works", diagnostic: "Diagnostic", start: "Start diagnostic" },
  hero: { ...enUS.hero, description: "Wesley combines websites, WhatsApp automation and AI to help your business explain its offer better, respond more clearly and guide every contact to the next step.", primaryCta: "View my free diagnostic", secondaryCta: "Understand the process" },
  solutions: { ...enUS.solutions, cards: [{ title: "Websites that position", text: "Pages that explain your solution, build trust and clearly show the next step." }, { title: "WhatsApp that organises", text: "Service flows to respond, qualify and transfer context to your team." }, { title: "AI with clear limits", text: "Automation with approved topics, a human route and continuous improvement as operations evolve." }] },
  process: { ...enUS.process, description: "You do not need to start with a huge project. Altixdev starts by understanding the goal, the bottleneck and the smallest change that can create learning before expanding any automation.", steps: [{ title: "Discover", text: "We map goal, channel, bottleneck and urgency." }, { title: "Design", text: "We connect message, website, WhatsApp and people." }, { title: "Implement", text: "We build with scope, limits and owners." }, { title: "Evolve", text: "We measure, adjust and expand what makes sense." }] },
  diagnostic: { ...enUS.diagnostic, questionSteps: [{ eyebrow: "01 · Desired outcome", title: "What do you want to make more efficient now?", options: ["Create more opportunities", "Convert more contacts", "Reduce manual tasks", "Organise a digital operation"] }, ...enUS.diagnostic.questionSteps.slice(1)] },
};

export const siteCopy: Record<Locale, SiteCopy> = {
  "pt-BR": ptBR,
  "en-US": enUS,
  es,
  "pt-PT": ptPT,
  de,
  nl,
  "en-GB": enGB,
  ru,
  nb,
  ga,
};

export const privateAccessLabels: Record<Locale, string> = {
  "pt-BR": "Acesso privado",
  "en-US": "Private access",
  es: "Acceso privado",
  "pt-PT": "Acesso privado",
  de: "Privater Zugang",
  nl: "Privétoegang",
  "en-GB": "Private access",
  ru: "Приватный доступ",
  nb: "Privat tilgang",
  ga: "Rochtain phríobháideach",
};

export const emailPlaceholders: Record<Locale, string> = {
  "pt-BR": "voce@empresa.com",
  "en-US": "email@company.com",
  es: "correo@empresa.com",
  "pt-PT": "email@empresa.pt",
  de: "email@unternehmen.de",
  nl: "e-mail@bedrijf.nl",
  "en-GB": "email@company.co.uk",
  ru: "email@company.ru",
  nb: "e-post@bedrift.no",
  ga: "rphost@comhlacht.ie",
};

export function isLocale(value: string | null): value is Locale {
  return localeOptions.some(option => option.code === value);
}

export function getSiteCopy(locale: Locale): SiteCopy {
  return siteCopy[locale];
}
